config/routes.rb
Rails.application.routes.draw do


  devise_for :users

	root to: 'items#index'
  resources :items
  resources :payments
  resources :orders
  resources :carts
  resources :recap_orders, only: [:index]

  resources :users, only: [:show, :edit, :update] do
    resources :avatars, only: [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  
  belongs_to :user
  has_many :orders

  def total
    self.orders.to_a.sum(&:total)
  end

end

app/models/item.rb
class Item < ApplicationRecord
	validates :title, presence: true
	validates :description, presence: true
	validates :price, presence: true
	validates :image_url, presence: true
	validates :description, length: {in: 10..100}

  has_many :orders

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :item
  belongs_to :cart
  belongs_to :recap_order, optional: true

  def total
    item.price
  end

end

app/models/recap_order.rb
class RecapOrder < ApplicationRecord

  belongs_to :user
  has_many :orders

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :first_name,
    presence: true,
    length: { in: 2..20 }
  validates :last_name,
    presence: true,
    length: { in: 2..20 }
    
  has_one_attached :avatar

  has_one :cart
  has_many :recap_orders

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  #french translation (still to be perfected)
  before_action do
    I18n.locale = :fr # Or whatever logic you use to choose.
  end
  # Config flash for the whole app --> To keep?
  # add_flash_types :success, :danger, :info, :warning, :alert

  # Include first name and last name into Devise process


  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password)}
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :authenticate_user!
    before_action :cart_exists?
    before_action :is_my_cart?, only: [:show]

  def new
    @cart = Cart.new
  end

  def create
    @cart = Cart.create(cart_params)
    
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @cart = Cart.find(params[:id])
  end

private

  def cart_params
    params.fetch(:cart, {})
  end

  def cart_exists?
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound  
      flash[:warning] = "Oups, on dirait que ce panier n'existe pas encore 😬"
      redirect_to root_path
    end
  end
  
  def is_my_cart?
    if Cart.find(params[:id]).user_id != current_user.id
      flash[:warning] = "Ah bon on va sur les paniers des autres pour vérifier que le controller est sécure 😁 ?"
      redirect_to root_path
    end
  end

end

app/controllers/concerns/current_cart.rb
module CurrentCart

  def set_cart
    @cart = Cart.find_or_create_by(user_id: current_user.id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
  	@items = Item.all
  end

  def show
  	@item = Item.find(params[:id])
    @item_rand = Item.all.reject {|item| item == @item }.sample(3)

  end


  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :authenticate_user!

  
  def new
    @order = Order.new
  end

  def create
    item = Item.find(params[:item_id])
    @order = @cart.orders.create(item: item)
    #flash[:notice] = "Ajouté au panier !"
    #redirect_to root_path
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to cart_path(current_user.cart.id), notice: 'Element supprimé.' }
    end
  end

private

  def order_params
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def new
    @total = params[:total]
  end
  
  def create
    # Amount in cents
    @total = params[:total].to_d
    @user = current_user
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: (@total*100).to_i,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_payment_path

  else 
    
    create_recap_order(@user)
    mails_order(@user)
    reset_cart(@user)
  end

  private

  def mails_order(user)
    OrderMailer.items_email(user).deliver_now
    OrderMailer.purchase_confirm_admin(user).deliver_now
  end

  def create_recap_order(user)

    @recap_order = RecapOrder.create(user: user)

    user.cart.orders.each do |order|
      order.update(recap_order: @recap_order)
    end
  end

  def reset_cart(user)
    cart = user.cart
    cart.orders.delete_all
  end
end

app/controllers/recap_orders_controller.rb
class RecapOrdersController < ApplicationController

  def index
    @recap_orders = RecapOrder.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user_exists?, :check_user, only: [:show]

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = "Bien joué ! Ton profil a été modifié 🎉"
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "Oups ! On ne peut pas modifier ton profil pour les raisons suivantes :"
      render :edit
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:first_name, :last_name, :avatar)
  end

  def user_exists?
    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound  
      flash[:warning] = "Oups, on dirait que ce compte n'existe pas encore 😬"
      redirect_to root_path
    end
  end

  def check_user
    @user = User.find(params[:id])
    unless current_user.id == @user.id
      flash[:warning] = "Bien essayé 😁"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/recap_orders_helper.rb
module RecapOrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<div class="container my-5", style="width:700px">

  <h1 class="mb-5">Liste des produits du panier</h1>
    
  <% @cart.orders.each do |item| %>
  
    <p><div class="d-flex flex-row align-items-center mb-3">
      <%= image_tag item.item.image_url, class: "image-md mr-3" %>
      <%= item.item.title %> - <%= number_to_currency(item.item.price, unit: "€", separator: ".", format: "%n %u") %> 
     
    <%= button_to "supprimer du panier", item, method: :delete, data: { confirm: "Êtes-vous sûr ?" }, class: "btn btn-secondary btn-sm ml-3" %>
      </div>
    </p>
    <% end %>
  
    <h4 class="mt-5">Sous-total panier : <%= number_to_currency(@cart.total, unit: "€", separator: ".", format: "%n %u") %></h4>


<p>Sous-total Panier :</p>
<p class=""><%= number_to_currency(@cart.total, unit: "€", separator: ".", format: "%n %u") %></p>

<% if @cart.total.to_d > 1 %>
  <%= link_to "Passer commande", new_payment_path(total: @cart.total), class: "btn btn-primary"%>
<% end %>


</div>

app/views/items/_kitten_card_1.html.erb
<div class="card border-light mb-4 animate-up-5">
  <div class="row no-gutters align-items-center">
    <div class="col-12 col-lg-6 col-xl-5" style="height: 300px;">
      <a href="<%= item_path(item.id) %>">
        
        <%= image_tag item.image_url, :alt => "kitten img", class:"card-img p-2 rounded-xl", style: "height: 300px; width: auto" %>
      </a>
    </div>
    <div class="col-12 col-lg-6 col-xl-7">
      <div class="card-body">
        <a href="<%= item_path(item.id) %>">
          <h4 class="h5"><%= item.title %></h4>
        </a>
        <div class="d-flex my-3">
          <span class="star fas fa-star text-warning"></span> 
          <span class="star fas fa-star text-warning"></span> 
          <span class="star fas fa-star text-warning"></span> 
          <span class="star fas fa-star text-warning"></span> 
          <span class="star fas fa-star text-warning"></span>
          <span class="badge badge-pill badge-primary ml-2">5</span>
        </div> 
        <div class="d-flex my-3">
          <%= item.description %>
        </div>
        <div class="d-flex justify-content-between">
          <div class="col pl-0">
            <span class="text-muted font-small d-block">Prix</span>
            <span class="h6 text-dark font-weight-bold"><%= item.price %> €</span>
          </div>
          <%# on pourrais rajouter une colone nombre de fois vendu si on as le temps
            <div class="col">
              <span class="text-muted font-small d-block mb-2">People</span>
              <span class="h5 text-dark font-weight-bold">24</span>
            </div>
          %>
          <% if user_signed_in? %>
            <div class="col">
              <%= link_to "Ajouter au panier", orders_path(item_id: item.id), method: 'POST' , class: "btn btn-primary"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/_kitten_card_2.html.erb
<div class="col-12 col-sm-6 col-lg-4">
  <div class="card border-light mb-4 animate-up-5">
    <a href="<%= item_path(item.id) %>" class="position-relative">
      <%= image_tag item.image_url, :alt => "kitten img", class:"card-img-top rounded-xl p-2" %>


   </a>
    <div class="card-body">
      <a href="<%= item_path(item.id) %>">
        <h4 class="h5"><%= item.title %></h4>
      </a>
      <div class="d-flex my-4">
        <span class="star fas fa-star text-warning"></span> 
        <span class="star fas fa-star text-warning"></span> 
        <span class="star fas fa-star text-warning"></span> 
        <span class="star fas fa-star text-warning"></span> 
        <span class="star fas fa-star text-warning"></span>
        <span class="badge badge-pill badge-primary ml-2">5.0</span>
      </div> 
      <div class="d-flex my-4">
        <%= item.description %>
      </div>
    </div>
    <div class="card-footer bg-soft border-top">
      <div class="d-flex justify-content-between">
        <div class="col pl-0">
          <span class="text-muted font-small d-block mb-2">Prix</span>
          <span class="h5 text-dark font-weight-bold"><%= item.price %> €</span>
        </div>
        <%# on pourrais rajouter une colone nombre de fois vendu si on as le temps
        <div class="col">
          <span class="text-muted font-small d-block mb-2">People</span>
          <span class="h5 text-dark font-weight-bold">24</span>
        </div>
        %>
        <% if user_signed_in? %>
          <div class="col">
            <%= link_to "Ajouter au panier", orders_path(item_id: item.id), method: 'POST' , class: "btn btn-primary"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="section section-header section-image bg-tertiary overlay-primary text-white overflow-hidden pb-6" data-background="url(<%= asset_path "chaton_2.jpg" =%>)" style="background-image: url(<%= asset_path "banner.jpg" =%>);">
  <div class="container z-2">
    <div class="row justify-content-center pt-3">
      <div class="col-12 text-center">
        <h1 class="mb-5">Trouve la photo du <span class="font-weight-bolder">chaton</span> de tes rêves</h1>
      </div>
    </div>
  </div>
</div>

<div class="section section-lg pt-6">
  <div id="spaces-container" class="container">
    <div class="row">
      <div class="col-12">
        <div class="justify-content-between align-items-center d-none d-md-flex">
          <div class="mr-3">
            <h2 class="h5 mb-3 mb-md-0">Nous avons <span class="font-weiht-bolder text-primary"><%= @items.length %> </span>photos de chatons à vous proposer :</h2>
          </div>
          <div class="nav-wrapper position-relative p-0">
            <ul class="nav nav-pills small-pills" id="tab-34" role="tablist">
              <li class="nav-item pr-0">
                <a class="nav-link text-sm-center border-0 active" id="tab-link-example-14" data-toggle="tab" href="#link-example-14" role="tab" aria-controls="link-example-14" aria-selected="false">
                    <span class="nav-link-icon d-block"><span class="fas fa-th-large"></span></span>
                </a>
              </li>
              <li class="nav-item pr-0">
                <a class="nav-link text-sm-center border-0" id="tab-link-example-13" data-toggle="tab" href="#link-example-13" role="tab" aria-controls="link-example-13" aria-selected="true">
                    <span class="nav-link-icon d-block"><span class="fas fa-th-list"></span></span>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="tab-content mt-4 mt-lg-4" id="tabcontentexample-5">
          <div class="tab-pane fade" id="link-example-13" role="tabpanel" aria-labelledby="tab-link-example-13">
            <div class="row justify-content-center">
              <div class="col-12 col-sm-10 col-md-6 col-lg-12 mb-4">
                <!-- Card 1-->


                <% @items.each do |item| %>
                  <%= render 'kitten_card_1', item: item %>
                <%end%>
                <!-- End of Card -->
              </div>
            </div>
          </div>
          <div class="tab-pane fade show active" id="link-example-14" role="tabpanel" aria-labelledby="tab-link-example-14">
            <div class="row">
              <!-- Card 2-->
              <% @items.each do |item| %>
                <%= render 'kitten_card_2', item: item %>
              <%end%>
              <!-- End of Card -->
            </div>
          </div>
          <%# si on veux on poura faire des gage de navigation
          <div class="col mt-3 d-flex justify-content-center">
            <nav aria-label="Page navigation example">
              <ul class="pagination">
                <li class="page-item disabled"><a class="page-link" tabindex="-1" href="#">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item active"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">4</a></li>
                <li class="page-item"><a class="page-link" href="#">5</a></li>
                <li class="page-item"><a class="page-link" href="#">Next</a></li>
              </ul>
            </nav>
          </div>
          %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
 <main>
        <!-- Hero -->

        <div class="section section-lg pt-5">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-lg-8">
                        
                        <div class="tab-content mt-5 mb-3" id="nav-tabContent">
                            <div class="tab-pane fade show active" id="nav-about" role="tabpanel" aria-labelledby="nav-about-tab">
                                <div class="row mb-5">
                                    <div class="col-12">                                            
                                        <%= image_tag @item.image_url, :alt => "kitten img", class:"rounded" %>                                             

                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                    
                    
                    <aside class="col-12 col-lg-4 mt-3 mt-lg-0 mb-5 pt-6">
                       <h2><%= @item.title %> </h2>

                            <p class="mt-5"> <%= @item.description %> </p>
                            <div class="d-flex my-4">
                                <span class="star fas fa-star text-warning"></span> 
                                <span class="star fas fa-star text-warning"></span> 
                                <span class="star fas fa-star text-warning"></span> 
                                <span class="star fas fa-star text-warning"></span> 
                                <span class="star fas fa-star text-warning"></span>
                                <span class="badge badge-pill badge-primary ml-2">5.0</span>
                              </div> 


                        
                                <%# on pourrais rajouter une colone nombre de fois vendu si on as le temps
                                <div class="col">
                                  <span class="text-muted font-small d-block mb-2">People</span>
                                  <span class="h5 text-dark font-weight-bold">24</span>
                                </div>
                                %>
                            <% if user_signed_in? %>
                            <div class="card bg-soft border-light p-3 mt-5">

                              <div class="d-flex justify-content-between">
                                <div class="col pl-0">
                                  <span class="text-muted font-small d-block mb-2">Prix</span>
                                  <span class="h5 text-dark font-weight-bold"><%= @item.price %> €</span>
                                </div>
                                <div class="col">
                                    <%= link_to "Ajouter au panier", orders_path(item_id: @item.id), method: 'POST' , class: "btn btn-primary"%>
                                </div>

                            <%else %>
                            <div class="card bg-soft border-light p-3 mt-5">

                              <div class="d-flex justify-content-between flex-column">
                                <div class="pl-0">
                                  <span class="text-muted font-small d-block mb-2">Prix</span>
                                  <span class="h5 text-dark font-weight-bold"><%= @item.price %> €</span>
                                </div>
                                <div class="d-flex mt-3">
                                    <%= link_to "Se connecter pour acheter cette image", new_user_session_path, class: "btn btn-primary"%>
                                </div>

                            <% end %>
                        </div>
  

                     </div>

                    </aside>
                </div>
            </div>
        </div>
        <section class="section bg-soft">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h4 class="mb-5 font-weight-bold">Les autres photos que vous pourriez aimer</h4>
                    </div>
            
                        <div class="tab-pane fade show active" id="link-example-14" role="tabpanel" aria-labelledby="tab-link-example-14">
                        <div class="row">
                          <!-- Cards-->
                          <% @item_rand.each do |item| %>

                              <div class="col-12 col-sm-6 col-lg-4">
                                  <div class="card border-light mb-4 animate-up-5">
                                    <a href="<%= item_path(item) %>" class="position-relative">
                                      <%= image_tag item.image_url, :alt => "kitten img", class:"card-img-top rounded-xl p-2" %>


                                   </a>
                                    <div class="card-body">
                                      <a href="<%= item_path(item) %>">
                                        <h4 class="h5"><%= item.title %></h4>
                                      </a>
                                      <div class="d-flex my-4">
                                        <span class="star fas fa-star text-warning"></span> 
                                        <span class="star fas fa-star text-warning"></span> 
                                        <span class="star fas fa-star text-warning"></span> 
                                        <span class="star fas fa-star text-warning"></span> 
                                        <span class="star fas fa-star text-warning"></span>
                                        <span class="badge badge-pill badge-primary ml-2">5.0</span>
                                      </div> 
                                      
                                    </div>
                                   
                                  </div>
                                </div>

                              <%end%>
                          <!-- End of Card -->
                        </div>
                      
                      </div>

                </div>
            </div>
        </section>
        <!-- End of section -->
    </main>

app/views/orders/show.html.erb
show.html.erb

app/views/payments/create.html.erb
<div class="container text-center my-5">
<h2>Merci pour votre commande </h2> 
<p>Votre commande de <strong><%= number_to_currency(@total, unit: "€", separator: ".", format: "%n %u") %></strong> a bein été enrgegistré</p>
</div>

app/views/payments/new.html.erb
<div class="container text-center my-5">

<%= form_tag payments_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Total: <%= number_to_currency(@total, unit: "€", separator: ".", format: "%n %u") %></span>
    </label>
  </article>

  <input name="total" type="hidden" value=<%= @total %>>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Payer pour les chattons"
    data-amount="<%= @total.to_d*100 %>"
    data-currency="eur"
    data-locale="auto">
  </script>
<% end %>
</div>

app/views/recap_orders/index.html.erb
<h1> Voici la liste de tes commande </h1>

<% @recap_orders.where(user_id: current_user.id).each_with_index do |recap_order, index| %>
  <h3> Ta Commande n°<%= index + 1%> :</h3>
  <ul>
    <% recap_order.orders.each do |order| %>
      <li> <%= order.item.title %> - <%= number_to_currency(order.item.price, unit: "€", separator: ".", format: "%n %u") %> </li>
    <% end %>
  </ul>
<% end %>

app/views/users/edit.html.erb
<div class="container my-5", style="max-width:400px">
      
      <%= form_for @user, html: { class: "form-signin mt-3" } do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Modifier mon profil</h1>

        <div class="form-group">
          <%= f.label "Prénom" %><br />
          <%= f.text_field :first_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label "Nom de famille" %><br />
          <%= f.text_field :last_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label "Photo de profil" %><br />
          <%= f.file_field :avatar, class: "form-control" %>
        </div>

        <div class="actions mt-5">
          <%= f.submit "Modifier", class: "btn btn-lg btn-primary btn-block" %>
        </div>

      <% end %>

</div>

app/views/users/show.html.erb
<div class="profile_canvas d-flex flex-column align-items-center">

  <%if @user.avatar.attached?%>
    <%= image_tag(@user.avatar, :alt => 'real avatar', class:'img-thumbnail profile_pic rounded-circle m-3', style: 'height:200px;width:200px') %>
  <%else%>
    <%= image_tag('unnamed.jpg', :alt => 'default avatar', class:'img-thumbnail profile_pic rounded-circle m-3', style: 'height:200px;width:200px') %>
  <%end%>

  <h2><%= @user.first_name %> <%= @user.last_name %></h2>

  <p> <strong>Adresse email :</strong> <%= @user.email %> </p>


  <div class="link_personal_settings">
      <%= link_to edit_user_path(current_user.id), class:"btn btn-light-custom-profile rounded d-flex mx-2 align-items-center", style:"height: 32px"  do %>
        <i class="fas fa-user mr-2"></i>
        <span>Modifier mon profil</span>
      <% end %>
    </div>

    <div class="link_personal_settings">
      <%= link_to edit_user_registration_path(current_user.id), class:"btn btn-light-custom-profile rounded d-flex mx-2 align-items-center", style:"height: 32px"  do %>
        <i class="fas fa-cog mr-2"></i>
        <span>Modifier mes informations</span>
      <% end %>
    </div>

    <div class="link_personal_settings">
      <%= link_to recap_orders_path, class:"btn btn-light-custom-profile rounded d-flex mx-2 align-items-center", style:"height: 32px"  do %>
        <i class=""></i>
        <span>Voir mes commandes</span>
      <% end %>
    </div>
</div>


</div>